#docker-compose.ymlのバージョン
version: '3'

#webサーバー、アプリケーション、DBコンテナの設定
services:
  web:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - '3000:3000'
    environment:
      PORT: '3000'
      HOST: '0.0.0.0'
    volumes:
      - ./:/app
    tty: true
